<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ktsu.Semantics.Color" Version="5.4.2" />
    <PackageVersion Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageVersion Include="ktsu.ImGui.App" Version="3.38.7" />
    <PackageVersion Include="Polyfill" Version="11.4.0" />
    <PackageVersion Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
</Project>
