<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />

  <ItemGroup>
    <ProjectReference Include="..\ThemeProvider\ThemeProvider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" />
    <PackageReference Include="ktsu.Semantics.Color" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <PackageReference Include="System.Numerics.Vectors" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="System.Memory" />
  </ItemGroup>

</Project>
