// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.ThemeProvider.UITests.Gallery;

using System.Collections.Generic;
using System.Text;

/// <summary>Writes the gallery's <c>README.md</c>, which captions each picture.</summary>
internal static class GalleryIndex
{
	/// <summary>Renders the index for the given entries, in catalog order.</summary>
	internal static string Render(IReadOnlyList<GalleryEntry> entries)
	{
		StringBuilder text = new();
		text.Append("# Theme gallery\n\n");
		text.Append("<!-- Generated by tests/ThemeProvider.UITests/Gallery. Edit GalleryCatalog.cs, not this file. -->\n\n");
		text.Append("Every theme in `ThemeRegistry.AllThemes` as Dear ImGui draws it through `ImGuiPaletteMapper`, ");
		text.Append("rendered headlessly by the UI test harness. Each picture is the same sample window: common widgets, ");
		text.Append("a table, semantic text, and the theme's full semantic palette, one row per meaning and one swatch per priority. ");
		text.Append("The pictures are regenerated on every successful build of `main`, so they show the current palettes.\n\n");

		foreach (GalleryEntry entry in entries)
		{
			text.Append("## ").Append(entry.Name).Append("\n\n");
			text.Append(entry.Description).Append("\n\n");
			text.Append("![").Append(entry.Name).Append("](").Append(entry.Slug).Append(".png)\n\n");
		}

		return text.ToString();
	}
}
